pipeline:

  flake8-web:
    image: python:2.7.12
    commands:
      - pip install -q flake8
      - flake8 .

  test:
    image: python:2.7.12
    commands:
      - pip install -Ur requirements.txt
      - pytest tests/unit/
    when:
      branch: [ master ]
