language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt

script:
  - unexport AWS_DEFAULT_REGION
  - unexport AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
  - pytest tests/unit/ -v